# Change {"ods_orderitem_ipd"} to {"xxx"}

# must have data after hive ddl
SELECT TBL_ID, DB_ID, TBL_NAME, TBL_TYPE FROM TBLS WHERE TBL_NAME = 'ods_orders_ipd';
SELECT SD_ID, LOCATION FROM SDS WHERE SD_ID = (SELECT SD_ID FROM TBLS WHERE TBL_NAME = 'ods_orders_ipd');
SELECT PARAM_KEY, PARAM_VALUE FROM TABLE_PARAMS WHERE TBL_ID = (SELECT TBL_ID FROM TBLS WHERE TBL_NAME = 'ods_orders_ipd');
SELECT PKEY_NAME, PKEY_TYPE FROM PARTITION_KEYS WHERE TBL_ID = (SELECT TBL_ID FROM TBLS WHERE TBL_NAME = 'ods_orders_ipd');

# for partition tables
# SELECT * FROM PARTITIONS;
SELECT PART_ID, PART_NAME, TBL_ID FROM PARTITIONS WHERE TBL_ID = (SELECT TBL_ID FROM TBLS WHERE TBL_NAME = 'ods_orders_ipd');

# Add Partitions metadata
INSERT INTO PARTITIONS (PART_ID, PART_NAME, TBL_ID, SD_ID, CREATE_TIME, LAST_ACCESS_TIME)
SELECT
    COALESCE(MAX_PART_ID + 1, 1) AS PART_ID,
    'data_date=2024-03-10',
    tbl.TBL_ID,
    sd.SD_ID + 1,
    UNIX_TIMESTAMP(),
    0
FROM
    (SELECT COALESCE(MAX(PART_ID), 0) AS MAX_PART_ID FROM PARTITIONS) AS p,
    (SELECT TBL_ID FROM TBLS WHERE TBL_NAME = 'ods_orderitem_ipd') AS tbl,
    (SELECT SD_ID FROM SDS ORDER BY SD_ID DESC LIMIT 1) AS sd;
