name: Start DWH Cluster

on:
  workflow_dispatch:

jobs:
  hadoop-cluster-start:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u smars-bin-hu --password-stdin

      - name: Pull Docker Images from Docker Hub
        run: |
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:hadoop-master-smars-1.1.2
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:hadoop-worker1-smars-1.1.2
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:hadoop-worker2-smars-1.1.2
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:mysql-hive-metastore-smars-1.1.2
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:hive-smars-1.1.2
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:spark-smars-1.1.1
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:oracle-oltp-smars-1.1.1
          docker pull ghcr.io/smars-bin-hu/proj1-dwh-cluster:airflow-smars-1.1.1

      - name: Start Big Data Cluster with Docker Compose
        run: |
          docker compose -f docker-compose-bigdata.yaml up -d

      - name: Show Running Containers (debug)
        run: |
          docker ps -a

      - name: Start Hadoop HA Cluster
        run: |
          bash start-hadoop-cluster.sh

      - name: Check JPS on hadoop-master
        run: |
          docker exec hadoop-master jps

      - name: Check JPS on hadoop-worker1
        run: |
          docker exec hadoop-worker1 jps

      - name: Check JPS on hadoop-worker2
        run: |
          docker exec hadoop-worker2 jps

      - name: Check HDFS HA status
        run: |
          echo "HDFS nn1:"
          docker exec hadoop-master hdfs haadmin -getServiceState nn1
          echo "HDFS nn2:"
          docker exec hadoop-master hdfs haadmin -getServiceState nn2

      - name: Check YARN HA status
        run: |
          echo "YARN rm1:"
          docker exec hadoop-master yarn rmadmin -getServiceState rm1
          echo "YARN rm2:"
          docker exec hadoop-master yarn rmadmin -getServiceState rm2
